name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: "2TaAcoZ7QTUiaDfyvZaiJ1m4YYi_4WQrsAcgF3Hnu7tU5Uqn4"

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Download file from spysnet.com
      run: |
        Invoke-WebRequest https://spysnet.com/tools -OutFile $Env:USERPROFILE\Downloads\myfile.zip

    - name: Extract file to Downloads
      run: Expand-Archive $Env:USERPROFILE\Downloads\myfile.zip -DestinationPath $Env:USERPROFILE\Downloads

    - name: Launch Chrome
      run: Start-Process "C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-features=LockProfileCookieDatabase

    - name: Create Tunnel
      run: .\ngrok\ngrok.exe http --url=vocal-duly-polliwog.ngrok-free.app 3389
